"""
newd2p - Application Constants
"""

MAX_FILE_SIZE_MB = 50
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

MAX_PAGES = 50
MAX_CHARACTERS = 500000

MIN_SLIDES = 6
MAX_SLIDES = 15
DEFAULT_SLIDES = 10

DEFAULT_SECONDS_PER_SLIDE = 45
MIN_SECONDS_PER_SLIDE = 20
MAX_SECONDS_PER_SLIDE = 120

MAX_CHARTS_PER_PRESENTATION = 5
CHART_DPI = 150
CHART_WIDTH_INCHES = 8
CHART_HEIGHT_INCHES = 5